### ISSUE TITLE
WireMockExercises6dot4Test.java getResponse_checkHeaders_shouldIncludeThoseAddedbyResponseDefinitionTransformer() is not correct

### ISSUE THREAD

**Issue by tangsiwei0831** [basdijkstra/wiremock-workshop#4]
the line  get("/response-definition-transformer") should be post("/requestLoan") like in your answers module

**Comment by basdijkstra** [comment]
Thank you, @tangsiwei0831, and apologies for the late reply. I'm overhauling this workshop at the moment, so this will be 'automatically' addressed.
